name: Docker - Manager

on:
  push:
    branches: ["main"]
    paths:
      - "Manager/**"
      - ".github/workflows/docker-manager.yml"
  push:
    tags: ["v*"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-buildx-action@v3

      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Generowanie tag√≥w:
      # - main: latest + sha-short + build-N
      # - tag v*: vX.Y.Z + sha-short
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            wookashi/featureswitcher-manager
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
            type=sha,format=short
            type=raw,value=build-{{run_number}},enable={{is_default_branch}}
            type=ref,event=tag

      - name: Build & push
        uses: docker/build-push-action@v5
        with:
          context: ./Manager
          file: ./Manager/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
